------4A------
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
BEGIN TRANSACTION
-----T1---------
SELECT * FROM FACULTY WHERE FACULTY = 'ТПР';

ROLLBACK;


-----5A-----
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
BEGIN TRANSACTION
SELECT * FROM SUBJECT WHERE SUBJECT = 'СУБД';
-------------------------- T1 ------------------
-------------------------- T2 -----------------
SELECT * FROM SUBJECT WHERE SUBJECT = 'СУБД';
COMMIT TRAN;

--------6A---------
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
BEGIN TRANSACTION
SELECT SUBJECT FROM SUBJECT WHERE SUBJECT = 'БД';
--------T1---------
--------T2---------

SELECT CASE
WHEN PULPIT = 'ИСиТ' THEN 'INSERT'  
ELSE ' ' 
END,
SUBJECT FROM SUBJECT WHERE PULPIT = 'ИСиТ'
ROLLBACK

--7A---
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE 
BEGIN TRANSACTION 
DELETE AUDITORIUM WHERE AUDITORIUM = '206-1'
INSERT AUDITORIUM VALUES ('206-1', 'ЛК', 123, '206-1')
UPDATE AUDITORIUM SET AUDITORIUM_NAME = '206-1' WHERE AUDITORIUM = '206-1'
--------T1---------
SELECT AUDITORIUM FROM AUDITORIUM WHERE AUDITORIUM = '206-1'
--------T2---------
ROLLBACK 	

SELECT AUDITORIUM FROM AUDITORIUM WHERE AUDITORIUM = '206-1'


