use UNIVER
--z1

SELECT FACULTY.FACULTY,GROUPS.PROFESSION,PROGRESS.SUBJECT,AVG(PROGRESS.NOTE)[ср. оценка]
		FROM FACULTY 
		Inner Join GROUPS 
		on FACULTY.FACULTY = GROUPS.FACULTY 
		Inner Join STUDENT 
		on GROUPS.IDGROUP = STUDENT.IDGROUP 
		Inner Join PROGRESS 
		on STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
		WHERE FACULTY.FACULTY in ('ИДиП')
		GROUP BY ROLLUP (FACULTY.FACULTY,GROUPS.PROFESSION,PROGRESS.SUBJECT)


SELECT FACULTY.FACULTY,GROUPS.PROFESSION,PROGRESS.SUBJECT,AVG(PROGRESS.NOTE)
		FROM FACULTY 
		Inner Join GROUPS 
		on FACULTY.FACULTY = GROUPS.FACULTY 
		Inner Join STUDENT 
		on GROUPS.IDGROUP = STUDENT.IDGROUP 
		Inner Join PROGRESS 
		on STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
		WHERE FACULTY.FACULTY in ('ИДиП')
		GROUP BY FACULTY.FACULTY,GROUPS.PROFESSION,PROGRESS.SUBJECT


--z2

SELECT FACULTY.FACULTY,GROUPS.PROFESSION,PROGRESS.SUBJECT,AVG(PROGRESS.NOTE)
		FROM FACULTY 
		Inner Join GROUPS 
		on FACULTY.FACULTY = GROUPS.FACULTY 
		Inner Join STUDENT 
		on GROUPS.IDGROUP = STUDENT.IDGROUP 
		Inner Join PROGRESS 
		on STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
		WHERE FACULTY.FACULTY in ('ИДиП')
		GROUP BY CUBE (FACULTY.FACULTY,GROUPS.PROFESSION,PROGRESS.SUBJECT)

--z3

SELECT FACULTY.FACULTY,GROUPS.PROFESSION,PROGRESS.SUBJECT,AVG(PROGRESS.NOTE)
		FROM FACULTY 
		Inner Join GROUPS 
		on FACULTY.FACULTY = GROUPS.FACULTY 
		Inner Join STUDENT 
		on GROUPS.IDGROUP = STUDENT.IDGROUP 
		Inner Join PROGRESS 
		on STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
		WHERE FACULTY.FACULTY in ('ИДиП')
		GROUP BY FACULTY.FACULTY,GROUPS.PROFESSION,PROGRESS.SUBJECT
UNION

SELECT FACULTY.FACULTY,GROUPS.PROFESSION,PROGRESS.SUBJECT,AVG(PROGRESS.NOTE)
		FROM FACULTY 
		Inner Join GROUPS 
		on FACULTY.FACULTY = GROUPS.FACULTY 
		Inner Join STUDENT 
		on GROUPS.IDGROUP = STUDENT.IDGROUP 
		Inner Join PROGRESS 
		on STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
		WHERE FACULTY.FACULTY in ('ХТиТ')
		GROUP BY FACULTY.FACULTY,GROUPS.PROFESSION,PROGRESS.SUBJECT



--UNION ALL

SELECT FACULTY.FACULTY,GROUPS.PROFESSION,PROGRESS.SUBJECT,AVG(PROGRESS.NOTE)
		FROM FACULTY 
		Inner Join GROUPS 
		on FACULTY.FACULTY = GROUPS.FACULTY 
		Inner Join STUDENT 
		on GROUPS.IDGROUP = STUDENT.IDGROUP 
		Inner Join PROGRESS 
		on STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
		WHERE FACULTY.FACULTY in ('ИДиП')
		GROUP BY FACULTY.FACULTY,GROUPS.PROFESSION,PROGRESS.SUBJECT
UNION ALL

SELECT FACULTY.FACULTY,GROUPS.PROFESSION,PROGRESS.SUBJECT,AVG(PROGRESS.NOTE)
		FROM FACULTY 
		Inner Join GROUPS 
		on FACULTY.FACULTY = GROUPS.FACULTY 
		Inner Join STUDENT 
		on GROUPS.IDGROUP = STUDENT.IDGROUP 
		Inner Join PROGRESS 
		on STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
		WHERE FACULTY.FACULTY in ('ИДиП')
		GROUP BY FACULTY.FACULTY,GROUPS.PROFESSION,PROGRESS.SUBJECT

--4z


SELECT FACULTY.FACULTY,GROUPS.PROFESSION,PROGRESS.SUBJECT,AVG(PROGRESS.NOTE)
		FROM FACULTY 
		Inner Join GROUPS 
		on FACULTY.FACULTY = GROUPS.FACULTY 
		Inner Join STUDENT 
		on GROUPS.IDGROUP = STUDENT.IDGROUP 
		Inner Join PROGRESS 
		on STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
		WHERE FACULTY.FACULTY in ('ИДиП')
		GROUP BY FACULTY.FACULTY,GROUPS.PROFESSION,PROGRESS.SUBJECT
UNION

SELECT FACULTY.FACULTY,GROUPS.PROFESSION,PROGRESS.SUBJECT,AVG(PROGRESS.NOTE)
		FROM FACULTY 
		Inner Join GROUPS 
		on FACULTY.FACULTY = GROUPS.FACULTY 
		Inner Join STUDENT 
		on GROUPS.IDGROUP = STUDENT.IDGROUP 
		Inner Join PROGRESS 
		on STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
		WHERE FACULTY.FACULTY in ('ХТиТ')
		GROUP BY FACULTY.FACULTY,GROUPS.PROFESSION,PROGRESS.SUBJECT
INTERSECT

SELECT FACULTY.FACULTY,GROUPS.PROFESSION,PROGRESS.SUBJECT,AVG(PROGRESS.NOTE)
		FROM FACULTY 
		Inner Join GROUPS 
		on FACULTY.FACULTY = GROUPS.FACULTY 
		Inner Join STUDENT 
		on GROUPS.IDGROUP = STUDENT.IDGROUP 
		Inner Join PROGRESS 
		on STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
		WHERE FACULTY.FACULTY in ('ИДиП')
		GROUP BY FACULTY.FACULTY,GROUPS.PROFESSION,PROGRESS.SUBJECT
UNION ALL

SELECT FACULTY.FACULTY,GROUPS.PROFESSION,PROGRESS.SUBJECT,AVG(PROGRESS.NOTE)
		FROM FACULTY 
		Inner Join GROUPS 
		on FACULTY.FACULTY = GROUPS.FACULTY 
		Inner Join STUDENT 
		on GROUPS.IDGROUP = STUDENT.IDGROUP 
		Inner Join PROGRESS 
		on STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
		WHERE FACULTY.FACULTY in ('ХТиТ')
		GROUP BY FACULTY.FACULTY,GROUPS.PROFESSION,PROGRESS.SUBJECT


--z5


SELECT FACULTY.FACULTY,GROUPS.PROFESSION,PROGRESS.SUBJECT,AVG(PROGRESS.NOTE)
		FROM FACULTY 
		Inner Join GROUPS 
		on FACULTY.FACULTY = GROUPS.FACULTY 
		Inner Join STUDENT 
		on GROUPS.IDGROUP = STUDENT.IDGROUP 
		Inner Join PROGRESS 
		on STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
		WHERE FACULTY.FACULTY in ('ИДиП')
		GROUP BY FACULTY.FACULTY,GROUPS.PROFESSION,PROGRESS.SUBJECT
UNION
SELECT FACULTY.FACULTY,GROUPS.PROFESSION,PROGRESS.SUBJECT,AVG(PROGRESS.NOTE)
		FROM FACULTY 
		Inner Join GROUPS 
		on FACULTY.FACULTY = GROUPS.FACULTY 
		Inner Join STUDENT 
		on GROUPS.IDGROUP = STUDENT.IDGROUP 
		Inner Join PROGRESS 
		on STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
		WHERE FACULTY.FACULTY in ('ХТиТ')
		GROUP BY FACULTY.FACULTY,GROUPS.PROFESSION,PROGRESS.SUBJECT
EXCEPT

SELECT FACULTY.FACULTY,GROUPS.PROFESSION,PROGRESS.SUBJECT,AVG(PROGRESS.NOTE)
		FROM FACULTY 
		Inner Join GROUPS 
		on FACULTY.FACULTY = GROUPS.FACULTY 
		Inner Join STUDENT 
		on GROUPS.IDGROUP = STUDENT.IDGROUP 
		Inner Join PROGRESS 
		on STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
		WHERE FACULTY.FACULTY in ('ИДиП')
		GROUP BY FACULTY.FACULTY,GROUPS.PROFESSION,PROGRESS.SUBJECT
UNION ALL

SELECT FACULTY.FACULTY,GROUPS.PROFESSION,PROGRESS.SUBJECT,AVG(PROGRESS.NOTE)
		FROM FACULTY 
		Inner Join GROUPS 
		on FACULTY.FACULTY = GROUPS.FACULTY 
		Inner Join STUDENT 
		on GROUPS.IDGROUP = STUDENT.IDGROUP 
		Inner Join PROGRESS 
		on STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
		WHERE FACULTY.FACULTY in ('ХТиТ')
		GROUP BY FACULTY.FACULTY,GROUPS.PROFESSION,PROGRESS.SUBJECT




--z6**


--z1*

use MSV_MyBase_2

SELECT Покупки.Товар ,Товары.Описание,AVG(Отделы.Потраченная_сумма)[ср. сумма] 
	FROM Покупки 
	Inner join Товары
	on Покупки.Товар = Товары.Название
	Inner join Отделы
	on Отделы.Название_товара = Товары.Название
	GROUP BY ROLLUP (Покупки.Товар,Товары.Описание)

	use MSV_MyBase_2


--z2*
SELECT Покупки.Товар ,Товары.Описание,AVG(Отделы.Потраченная_сумма)[ср. сумма] 
	FROM Покупки 
	Inner join Товары
	on Покупки.Товар = Товары.Название
	Inner join Отделы
	on Отделы.Название_товара = Товары.Название
	GROUP BY CUBE (Покупки.Товар,Товары.Описание)


--z3* 4 5

SELECT Покупки.Товар ,Товары.Описание
	FROM Покупки 
	Inner join Товары
	on Покупки.Товар = Товары.Название
	Inner join Отделы
	on Отделы.Название_товара = Товары.Название
	WHERE Товары.Описание in ('Описание1')
	GROUP BY Покупки.Товар,Товары.Описание
UNION

SELECT Покупки.Товар ,Товары.Описание
	FROM Покупки 
	Inner join Товары
	on Покупки.Товар = Товары.Название
	Inner join Отделы
	on Отделы.Название_товара = Товары.Название
	WHERE Товары.Описание in ('Описание2')
	GROUP BY Покупки.Товар,Товары.Описание
INTERSECT
SELECT Покупки.Товар ,Товары.Описание
	FROM Покупки 
	Inner join Товары
	on Покупки.Товар = Товары.Название
	Inner join Отделы
	on Отделы.Название_товара = Товары.Название
	WHERE Товары.Описание in ('Описание1')
	GROUP BY Покупки.Товар,Товары.Описание
UNION ALL

SELECT Покупки.Товар ,Товары.Описание
	FROM Покупки 
	Inner join Товары
	on Покупки.Товар = Товары.Название
	Inner join Отделы
	on Отделы.Название_товара = Товары.Название
	WHERE Товары.Описание in ('Описание2')
	GROUP BY Покупки.Товар,Товары.Описание




SELECT Покупки.Товар ,Товары.Описание
	FROM Покупки 
	Inner join Товары
	on Покупки.Товар = Товары.Название
	Inner join Отделы
	on Отделы.Название_товара = Товары.Название
	WHERE Товары.Описание in ('Описание1')
	GROUP BY Покупки.Товар,Товары.Описание
UNION

SELECT Покупки.Товар ,Товары.Описание
	FROM Покупки 
	Inner join Товары
	on Покупки.Товар = Товары.Название
	Inner join Отделы
	on Отделы.Название_товара = Товары.Название
	WHERE Товары.Описание in ('Описание2')
	GROUP BY Покупки.Товар,Товары.Описание
EXCEPT
SELECT Покупки.Товар ,Товары.Описание
	FROM Покупки 
	Inner join Товары
	on Покупки.Товар = Товары.Название
	Inner join Отделы
	on Отделы.Название_товара = Товары.Название
	WHERE Товары.Описание in ('Описание1')
	GROUP BY Покупки.Товар,Товары.Описание
UNION ALL

SELECT Покупки.Товар ,Товары.Описание
	FROM Покупки 
	Inner join Товары
	on Покупки.Товар = Товары.Название
	Inner join Отделы
	on Отделы.Название_товара = Товары.Название
	WHERE Товары.Описание in ('Описание2')
	GROUP BY Покупки.Товар,Товары.Описание

